name: Twitter Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/3 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
        id: setup-chrome

      - name: Install dependencies
        run: |
          npm install
          npm install puppeteer-extra puppeteer-extra-plugin-stealth
          
      - name: Run bot
        env:
          TWITTER_EMAIL: "gofokek187@inikale.com"
          TWITTER_PASSWORD: "aranciata1234"
          TWITTER_USERNAME: "trenchwizardai"
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
        run: |
          echo "Chrome path: $CHROME_PATH"
          node index.js
