name: Twitter Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/3 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
      - name: Install dependencies
        run: |
          npm install
          npm install puppeteer-extra puppeteer-extra-plugin-stealth
          
      - name: Run bot
        env:
          TWITTER_EMAIL: "gofokek187@inikale.com"
          TWITTER_PASSWORD: "aranciata1234"
          TWITTER_USERNAME: "trenchwizardai"
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
          PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome"
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 &
          export DISPLAY=:99
          node index.js